version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: infrastructure-zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: infrastructure-kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # ðŸ‘‡ FIX 1: Bind to all interfaces (Fixes Windows crash)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # ðŸ‘‡ FIX 2: Limit Memory usage (Fixes Exit Code 137 crash)
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"

  redis:
    image: redis:alpine
    container_name: infrastructure-redis-1
    ports:
      - "6379:6379"